import type { Metadata } from 'next';
import { CodeBlock, Footer, Header } from '../ui';

export const metadata: Metadata = { title: 'Install and connect your Strapi project', description: 'Run Safe Strapi MCP locally with your own environment file and Strapi schemas. No hosted account or shared access key required.', alternates: { canonical: '/docs' } };
const npmPackage = 'https://www.npmjs.com/package/safe-strapi-mcp';
const github = 'https://github.com/metehankasapp/safe-strapi-mcp';

export default function Docs() {
  return <main><Header /><div className="docsShell"><aside className="docsNav"><strong>Documentation</strong><a href="#get-started">Install</a><a href="#token">Create token</a><a href="#environment">Connect Strapi</a><a href="#client">MCP configuration</a><a href="#testing">First test</a><a href="#tools">Tools</a><a href="#requirements">Requirements</a><a href="#errors">Troubleshooting</a></aside><article className="docs">
    <span className="kicker">DOCUMENTATION</span><h1>Your client. Your Strapi.</h1><p className="lead">The recommended setup is to <a className="textLink" href="/#master-prompt">paste the master prompt into Codex</a> from your repository. It configures the local stdio package against your existing project. No hosted endpoint, MCP_API_KEY, or STRAPI_MCP_TOKEN is required.</p>
    <h2 id="get-started">1. Let Codex configure it</h2><p>Open Codex in the repository that contains your Strapi project and use the <a className="textLink" href="/#master-prompt">master prompt</a>. It inspects existing environment variables, configures a project-scoped local stdio server, and verifies it read-only. For manual setup, install Node.js 22.5 or newer, then install the latest npm release.</p><CodeBlock label="Terminal">{`npm install --global safe-strapi-mcp\nsafe-strapi-mcp --help`}</CodeBlock><p><a className="textLink" href={npmPackage}>View on npm</a> or <a className="textLink" href={github}>review the source on GitHub</a>. Releases are built from the public repository with npm provenance.</p>
    <h2 id="token">2. Create a Strapi API token</h2><p>In Strapi Admin, open <strong>Settings → Global settings → API Tokens → Create new API Token</strong>. Choose <strong>Custom</strong>. Grant <code>find</code> and <code>findOne</code> for the page collection, every populated relation, and Upload/media. Grant <code>create</code> and <code>update</code> only for collection types whose drafts Safe Strapi may create. Delete and publish permissions are not required.</p><p>Copy the token when Strapi displays it; the full value is shown only once. If page listing works but inspection returns HTTP 403, the token normally lacks read access to a populated relation or media collection.</p>
    <h2 id="environment">3. Connect your Strapi project</h2><p>Create a dedicated private environment file. Use the Strapi origin without <code>/admin</code> or <code>/api</code>, then paste the token after the equals sign.</p><CodeBlock label=".env.safe-strapi">{`STRAPI_URL=https://cms.example.com\nSTRAPI_API_TOKEN=paste-token-here`}</CodeBlock><p>Never commit this file or paste the token into chat. Add both the credential file and Safe Strapi state to the project’s gitignore.</p><CodeBlock label=".gitignore">{`.env.safe-strapi\n.safe-strapi/`}</CodeBlock><p>Point the tool at the Strapi source directory containing <code>src/api</code> and <code>src/components</code>. It discovers collection types with Draft &amp; Publish, a UID field, and a dynamic zone. Each discovered content type and zone appears in <code>list_projects</code>.</p><CodeBlock label="Optional configuration">{`STRAPI_PROJECT_ROOT=/absolute/path/to/strapi\nSTRAPI_CONTENT_TYPE=page\nSTRAPI_BLOCKS_FIELD=blocks\nSTRAPI_SLUG_FIELD=slug\nSTRAPI_TITLE_FIELD=title\nSTRAPI_LOCALE=en`}</CodeBlock><p>For an existing token variable such as <code>MY_CMS_TOKEN</code>, set <code>STRAPI_TOKEN_ENV=MY_CMS_TOKEN</code>. The tool reads that variable rather than requiring you to duplicate the secret.</p>
    <h2 id="client">4. Add it to your MCP client</h2><p>Use absolute paths. This Codex command runs the published npm package and keeps the secret in the env file:</p><CodeBlock label="Codex CLI">{`codex mcp add safe-strapi -- \\\n  npm exec --yes --package=safe-strapi-mcp -- safe-strapi-mcp \\\n  --env-file /absolute/path/to/strapi/.env.safe-strapi \\\n  --project-root /absolute/path/to/strapi\n\ncodex mcp get safe-strapi`}</CodeBlock><p>For another MCP client, use the equivalent stdio configuration:</p><CodeBlock label="MCP server configuration">{JSON.stringify({ mcpServers: { 'safe-strapi': { command: 'npm', args: ['exec', '--yes', '--package=safe-strapi-mcp', '--', 'safe-strapi-mcp', '--env-file', '/absolute/path/to/strapi/.env.safe-strapi', '--project-root', '/absolute/path/to/strapi'] } } }, null, 2)}</CodeBlock><p>The MCP process loads the file itself, so the secret does not appear in client configuration or chat. Restart the client after adding the server.</p>
    <h2 id="testing">5. Test before writing</h2><div className="promptList"><div><span>01</span><p>“Use Safe Strapi to list my projects and component schemas. Do not make changes.”</p></div><div><span>02</span><p>“Find the homepage in my project. Inspect its components and return its content hash. Do not write.”</p></div><div><span>03</span><p>“Preview a draft copy with a new hero title. Show the proposed changes before creating it.”</p></div><div><span>04</span><p>“Create the draft from that exact preview, validate it, and compare it with the source. Confirm the source hash stayed the same and nothing was published.”</p></div></div><p>Do not proceed to preview until both project listing and full page inspection succeed. Preview is read-only. The first write happens only when you explicitly approve draft creation.</p><p>Your AI client uses the environment file selected at setup. For another Strapi installation, add another named MCP server with its own file and source directory.</p><p>Continue with the <a className="textLink" href="/prompts">prompt cookbook</a> for copy-ready examples covering JSON input, component insertion, reordering, long pages, and production team workflows. Agents can fetch the same guide as raw Markdown from <a className="textLink" href="/prompts.md">/prompts.md</a>.</p>
    <h2 id="tools">Available tools</h2><p><code>list_projects</code>, <code>find_pages</code>, <code>inspect_page</code>, <code>list_components</code>, <code>get_component_schema</code>, <code>preview_clone_and_modify</code>, <code>clone_page_and_modify</code>, <code>inspect_owned_draft</code>, <code>modify_owned_draft</code>, <code>duplicate_component</code>, <code>replace_component</code>, <code>validate_draft</code>, and <code>compare_pages</code>.</p><p>Operations support insertion, patching, moving, duplication, replacement, and removal on draft copies. API indexes are zero-based and operations run in order. Inspect the current order before selecting a block. Publish reviewed content yourself in Strapi.</p>
    <h2 id="requirements">What is supported?</h2><p>Strapi 5 collection types with dynamic zones and Draft &amp; Publish. Localhost and remote CMS URLs both work when reachable from the machine running the MCP. Single types, automatic publishing, and arbitrary unknown schemas are not part of the automatic setup.</p><p>If you only have a remote URL and token, request the schema files from the project owner, or supply a <code>--config /absolute/path/projects.json</code> file with embedded component and content-type schemas. A normal content API token does not provide the complete schema catalog.</p><p>The ownership and retry database is stored at <code>.safe-strapi/audit.sqlite</code> inside the selected project by default. Keep it private, preserve it between sessions, and add <code>.safe-strapi/</code> to your gitignore. Deleting it removes the ownership records required to modify existing drafts.</p>
    <h2 id="errors">Troubleshooting</h2><p><code>CONFIG_ERROR</code>: check the source directory and supported content types. <code>TOKEN_MISSING</code>: check the selected env file and token variable name. <code>STRAPI_ERROR</code>: check the CMS URL, permissions, and population rules. <code>AMBIGUOUS_SELECTOR</code>: specify an index or occurrence. <code>SOURCE_CHANGED</code> or <code>DRAFT_CHANGED</code>: inspect and preview again. <code>DRAFT_NOT_OWNED</code>: only drafts registered in this installation’s audit database can be modified. <code>OPERATION_BUSY</code>: another MCP process is writing; retry later. <code>WRITE_OUTCOME_UNKNOWN</code>: Strapi may have accepted a create whose response was lost; inspect the CMS through the API before starting a new operation.</p><p>Writes are serialized when clients share the same audit database. Strapi REST has no atomic revision precondition for external writers, so avoiding every possible GET/PUT race requires a Strapi-side conditional-update endpoint.</p><p>Safe Strapi runs locally over stdio. If a client asks for an MCP access key, remove its hosted URL configuration and use the master prompt again.</p>
  </article></div><Footer /></main>;
}
