import type { Metadata } from 'next';
import { CodeBlock, Footer, Header } from '../ui';

export const metadata: Metadata = { title: 'Install and connect your Strapi project', description: 'Run Safe Strapi MCP locally with your own environment file and Strapi schemas. No hosted account or shared access key required.', alternates: { canonical: '/docs' } };
const npmPackage = 'https://www.npmjs.com/package/safe-strapi-mcp';
const github = 'https://github.com/metehankasapp/safe-strapi-mcp';

export default function Docs() {
  return <main><Header /><div className="docsShell"><aside className="docsNav"><strong>Documentation</strong><a href="#get-started">Install</a><a href="#environment">Connect Strapi</a><a href="#client">MCP configuration</a><a href="#testing">First test</a><a href="#tools">Tools</a><a href="#requirements">Requirements</a><a href="#errors">Troubleshooting</a></aside><article className="docs">
    <span className="kicker">DOCUMENTATION</span><h1>Your client. Your Strapi.</h1><p className="lead">Run Safe Strapi on your own machine or agent host. It reads your Strapi connection from a local environment file and talks directly to your CMS. No Safe Strapi account or shared access key is required.</p>
    <h2 id="get-started">1. Install the package</h2><p>Install Node.js 22.5 or newer, then install the latest npm release. Native SQLite dependencies may require build tools if a prebuilt binary is unavailable for your platform.</p><CodeBlock label="Terminal">{`npm install --global safe-strapi-mcp\nsafe-strapi-mcp --help`}</CodeBlock><p><a className="textLink" href={npmPackage}>View on npm</a> or <a className="textLink" href={github}>review the source on GitHub</a>. Releases are built from the public repository with npm provenance.</p>
    <h2 id="environment">2. Connect your Strapi project</h2><p>Add these variables to your private environment file. STRAPI_URL is your CMS URL, which may differ from your public website address. Paste your token after the equals sign in your local copy.</p><CodeBlock label="Your Strapi .env">{`STRAPI_URL=http://localhost:1337\nSTRAPI_API_TOKEN=`}</CodeBlock><p>Use a Strapi API token with find, findOne, create, and update permissions for the content types you intend to edit. Related media and content must be readable too. Keep this file out of version control.</p><p>Point the tool at the Strapi source directory containing <code>src/api</code> and <code>src/components</code>. It discovers collection types with Draft &amp; Publish, a UID field, and a dynamic zone. Each discovered content type and zone appears in <code>list_projects</code>.</p><CodeBlock label="Optional configuration">{`STRAPI_PROJECT_ROOT=/absolute/path/to/strapi\nSTRAPI_CONTENT_TYPE=page\nSTRAPI_BLOCKS_FIELD=blocks\nSTRAPI_SLUG_FIELD=slug\nSTRAPI_TITLE_FIELD=title\nSTRAPI_LOCALE=en`}</CodeBlock><p>For an existing token variable such as <code>MY_CMS_TOKEN</code>, set <code>STRAPI_TOKEN_ENV=MY_CMS_TOKEN</code>. The tool reads that variable rather than requiring you to duplicate the secret.</p>
    <h2 id="client">3. Add it to your MCP client</h2><p>Choose a local stdio server. Use the executable path returned by <code>which safe-strapi-mcp</code> on macOS/Linux or <code>where safe-strapi-mcp</code> on Windows. Set the arguments below using your own absolute paths.</p><CodeBlock label="MCP server configuration">{JSON.stringify({ mcpServers: { 'safe-strapi': { command: '/absolute/path/to/safe-strapi-mcp', args: ['--env-file', '/absolute/path/to/strapi/.env', '--project-root', '/absolute/path/to/strapi'] } } }, null, 2)}</CodeBlock><p>Client configuration formats vary; the command and arguments stay the same. The MCP process loads the file itself, so the secret does not need to appear in your client configuration or chat. Restart your client after adding the server.</p>
    <h2 id="testing">4. Start with a read-only test</h2><div className="promptList"><div><span>01</span><p>“Use Safe Strapi to list my projects and component schemas. Do not make changes.”</p></div><div><span>02</span><p>“Find the homepage in my project. Inspect its components and return its content hash.”</p></div><div><span>03</span><p>“Preview a draft copy with a new hero title. Show the proposed changes before creating it.”</p></div><div><span>04</span><p>“Create the draft from that preview, validate it, and compare it with the source. Confirm the source hash stayed the same.”</p></div></div><p>Your AI client uses the environment file selected at setup. For another Strapi installation, add another named MCP server with its own file and source directory.</p><p>Continue with the <a className="textLink" href="/prompts">prompt cookbook</a> for copy-ready examples covering JSON input, component insertion, reordering, long pages, and production team workflows. Agents can fetch the same guide as raw Markdown from <a className="textLink" href="/prompts.md">/prompts.md</a>.</p>
    <h2 id="tools">Available tools</h2><p><code>list_projects</code>, <code>find_pages</code>, <code>inspect_page</code>, <code>list_components</code>, <code>get_component_schema</code>, <code>preview_clone_and_modify</code>, <code>clone_page_and_modify</code>, <code>inspect_owned_draft</code>, <code>modify_owned_draft</code>, <code>duplicate_component</code>, <code>replace_component</code>, <code>validate_draft</code>, and <code>compare_pages</code>.</p><p>Operations support insertion, patching, moving, duplication, replacement, and removal on draft copies. API indexes are zero-based and operations run in order. Inspect the current order before selecting a block. Publish reviewed content yourself in Strapi.</p>
    <h2 id="requirements">What is supported?</h2><p>Strapi 5 collection types with dynamic zones and Draft &amp; Publish. Localhost and remote CMS URLs both work when reachable from the machine running the MCP. Single types, automatic publishing, and arbitrary unknown schemas are not part of the automatic setup.</p><p>If you only have a remote URL and token, request the schema files from the project owner, or supply a <code>--config /absolute/path/projects.json</code> file with embedded component and content-type schemas. A normal content API token does not provide the complete schema catalog.</p><p>The ownership and retry database is stored at <code>.safe-strapi/audit.sqlite</code> inside the selected project by default. Keep it private, preserve it between sessions, and add <code>.safe-strapi/</code> to your gitignore. Deleting it removes the ownership records required to modify existing drafts.</p>
    <h2 id="errors">Troubleshooting</h2><p><code>CONFIG_ERROR</code>: check the source directory and supported content types. <code>TOKEN_MISSING</code>: check the selected env file and token variable name. <code>STRAPI_ERROR</code>: check the CMS URL, permissions, and population rules. <code>AMBIGUOUS_SELECTOR</code>: specify an index or occurrence. <code>SOURCE_CHANGED</code> or <code>DRAFT_CHANGED</code>: inspect and preview again. <code>DRAFT_NOT_OWNED</code>: only drafts registered in this installation’s audit database can be modified. <code>OPERATION_BUSY</code>: another MCP process is writing; retry later. <code>WRITE_OUTCOME_UNKNOWN</code>: Strapi may have accepted a create whose response was lost; inspect the CMS through the API before starting a new operation.</p><p>Writes are serialized when clients share the same audit database. Strapi REST has no atomic revision precondition for external writers, so avoiding every possible GET/PUT race requires a Strapi-side conditional-update endpoint.</p><p>For an explicitly configured shared HTTP installation, the administrator supplies a separate MCP access key. That is an optional deployment mode, not a requirement for the local package.</p>
  </article></div><Footer /></main>;
}
